### ISSUE TITLE
Ohai plugin deprication warning

### ISSUE THREAD

**Issue by damacus** [miketheman/nginx#239]
/etc/chef/ohai_plugins/nginx.rb is a version 6 plugin this will be deprecated in future versions of ohai.

**Comment by spajus** [comment]
Few thoughts that could get this moving. Perhaps it would be possible to use node attributes to choose which ohai plugin version to use? Another option - to detect chef version and to choose which type of nginx ohai plugin to load accordingly?

**Comment by tas50** [comment]
#422 includes a fix for this by shipping a v7 plugin on v7+ hosts

**Comment by tas50** [comment]
This particular issue has been pulled into the chef_nginx cookbook 2.8.0 release. The chef_nginx cookbook is a fork of this cookbook with many of the outstanding issues in the 2.7.6 release resolved. The release is backwards compatible with this cookbook outside of the name change, which obviously requires updating runlist and and metadata dependencies. I'd highly suggest giving it a try to see if this resolves you nginx cookbook woes.

https://github.com/chef-cookbooks/chef_nginx
https://supermarket.chef.io/cookbooks/chef_nginx#changelog
