### ISSUE TITLE
Move matchers file to libraries directory

### ISSUE THREAD

**Issue by tejaycar** [miketheman/nginx#253]
Can you please move the Matchers.rb file for Chefspec into the libraries directory, rather than its current location?  That will allow authors that use your cookbook to automatically use your matchers in our own tests.

**Comment by miketheman** [comment]
There is no current `matchers.rb`. Nothing to move.

**Comment by tejaycar** [comment]
Not sure if I was mistaken in the first place, or if the file name has since changed, but the file is currently here: https://github.com/miketheman/nginx/blob/master/spec/support/matchers/nginx_site.rb

If you moved it into the libraries directory, then it would be available for cookbooks that depend on this one automatically.

**Comment by miketheman** [comment]
Sorry, I missed that. Moved.

**Comment by tejaycar** [comment]
No problem.  Thanks for moving it.
