### ISSUE TITLE
Nginx will not install without the 'which' package on Fedora 20

### ISSUE THREAD

**Issue by wernerb** [miketheman/nginx#255]
The following error happens on Fedora 20 without the which package installed. 

	================================================================================
	Error executing action `install` on resource 'package[nginx]'
	================================================================================

	Errno::ENOENT
	-------------
	No such file or directory - which nginx

	Resource Declaration:
	---------------------
	# In /var/chef/cookbooks/nginx/recipes/package.rb

	40: package node['nginx']['package_name'] do
	41:   options package_install_opts
	42:   notifies :reload, 'ohai[reload_nginx]', :immediately
	43:   not_if 'which nginx'
	44: end
	45:

	Compiled Resource:
	------------------
	# Declared in /var/chef/cookbooks/nginx/recipes/package.rb:40:in `from_file'

	package("nginx") do
	action :install
	retries 0
	retry_delay 2
	package_name "nginx"
	cookbook_name :nginx
	recipe_name "package"
	not_if "which nginx"
	end

**Comment by miketheman** [comment]
This is due to the detection mechanism to determine if the source or package is installed.

Agreed - the `which` package is expected to be there, and you could shim it in before the nginx recipe.

Since we're going to rewrite this, I don't think there's a good fix for right now.
