### ISSUE TITLE
Kitchen tests fail on Centos 5.1 

### ISSUE THREAD

**Issue by damacus** [miketheman/nginx#261]
The current tests only seem to be failing on Centos-5.1 with the following yum cache error: 

```
           ================================================================================
           Error executing action `create` on resource 'yum_repository[epel]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[yum-makecache-epel] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 53) had an error:
 Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
           STDOUT: 
           STDERR: Traceback (most recent call last):
             File "/usr/bin/yum", line 29, in ?
               yummain.user_main(sys.argv[1:], exit_code=True)
```

Basically... yum can't update because of a broken certificate.

**Comment by nkadel-skyhook** [comment]
EPEL's SSL certificates do not use the out of date CA certificates on old versions of CentOS. Install the CentOS 5.x updated copy of 'certificate-ca' package, or as a workaround disable SSL verification fo the yum-epel repository.

This needs to go in the 'yum-epel' cookbook.

**Comment by rmoriz** [comment]
Looks like a `yum`cookbook issue? Close?

**Comment by nkadel-skyhook** [comment]
It's not even a yum cookbook issue: it's a "maintain your OS security components" issue, especially SSL related packages.  But yeah, I'd close it and maybe make sure yum-epel has a note about this.

**Comment by rmoriz** [comment]
Sorry, meant `yum-epel`, not `yum`
