### ISSUE TITLE
Can't setup logformats to be used in nginx.conf

### ISSUE THREAD

**Issue by docwhat** [miketheman/nginx#293]
If you want custom logformats for access and error logs, you can't do it via the `node['nginx']['access_log_options']` and `node['nginx']['error_log_options']` attributes because the `conf.d` directory isn't included until after the logs are defined in `nginx.conf`.

I was trying to get all my logs to be in [JSON format](http://blog.pkhamre.com/2012/08/23/logging-to-logstash-json-format-in-nginx/).

I'm not sure what the right solution is, unless you create a special "formats.d" folder or something that gets included ASAP in `nginx.conf`.

**Comment by jrstarke** [comment]
Why not just create the log formats in a file like `conf.d/log_formats.conf`. You could generate this in a custom chef recipe using a template.

**Comment by docwhat** [comment]
@jrstarke it won't work for the error log because it is included after the main config. See the original comment.

**Comment by miketheman** [comment]
Solved by #302
