### ISSUE TITLE
vhost support via attributes

### ISSUE THREAD

**Issue by mike-pt** [miketheman/nginx#300]
From what I could see in the code this is not supported, I wonder however If you would consider adding support for this...

I'm speaking of something like the getchef cookbook witth the "apps" attribute.

Granted that I can jut use templates but It seems like a nice addiction, and sadly I'm not confortable enough with ruby/chef to fork and do it myself :P so I leave the suggestion here

Thanks

**Comment by rmoriz** [comment]
You should write a wrapper cookbook which deals with that.

**Comment by mike-pt** [comment]
@rmoriz I'm realy not a chef expert... but do you have any link to docs where I could find more info about it?

**Comment by rmoriz** [comment]
just create a cookbook 'nginx-vhosts' that depends on 'nginx'. here is some untested code I just made up, adjust to your needs. Hope you get the idea. 


#### metadata.rb

```ruby
…
depends 'nginx', '~>2.6.6'
…
```


#### attributes/default.rb
```
default['nginx-vhosts']['vhosts']['domain1.com']['root'] = '/srv/web/domain1/root'
default['nginx-vhosts']['vhosts']['domain1.com']['server_name'] = 'domain1.com www.domain1.com'
default['nginx-vhosts']['vhosts']['domain1.com']['template'] = 'generic.erb' 
default['nginx-vhosts']['vhosts']['domain1.com']['action'] = :create 

…
default['nginx-vhosts']['vhosts']['domain2.com']['root'] = '/srv/web/domain2/root'
default['nginx-vhosts']['vhosts']['domain3.com']['server_name'] = 'domain2.com www.domain2.com'
default['nginx-vhosts']['vhosts']['domain2.com']['template'] = 'generic.erb' 
default['nginx-vhosts']['vhosts']['domain2.com']['action'] = :create 

…
default['nginx-vhosts']['vhosts']['domain3.com']['root'] = '/srv/web/domain3/root'
default['nginx-vhosts']['vhosts']['domain3.com']['server_name'] = 'domain3.com www.domain3.com'
default['nginx-vhosts']['vhosts']['domain3.com']['template'] = 'generic.erb' 
default['nginx-vhosts']['vhosts']['domain3.com']['action'] = :create 
…
```

#### templates/generic.erb

```nginx

server {
        listen   80; 
      
        root <%= @config['root'] %>;
        index index.html index.htm;
				
        server_name <%= @config['server_name'] %>;
				…
				
}
```

#### recipes/default.rb
```ruby
include_recipe 'nginx::default'

node['nginx-vhosts']['vhosts'].each do |domain, config| 
  template "/etc/nginx/sites-availble/#{domain}" do
    source config['template']
    action config['action']
    varibles(
      config: config
    )
  end
  
  nginx_site domain do
    enable (config['action'].to_sym == :create)
    notifies :reload, 'service[nginx]', :delayed
  end
end

**Comment by mike-pt** [comment]
oh ok when you mentioned wrapper this didn't crossed my mind and I've seen this in use a few times!

thanks for sharing, I guess I should close the "issue" anyway as there's is a easy way to do it ourselfs
