### ISSUE TITLE
Use ":delayed" for all service restarts that are not ":immediately"

### ISSUE THREAD

**Issue by nkadel-skyhook** [miketheman/nginx#328]
The standard "restart" option occurs immediately, before all configuration files are necessarily deployed. This means that if a config file being removed or disabled conflicts with a new file, and is presented in the wrong order, the restart will fail until it is manually cleared.

It's very easy to fix by using ":delayed" in all relevant restart options. The fix is in pull request 327.

**Comment by DrMerlin** [comment]
Yes, please!

**Comment by miketheman** [comment]
As mentioned in https://github.com/miketheman/nginx/pull/327 - the default for the service is `:delayed`.

**Comment by nkadel-skyhook** [comment]
And yet, it didn't work that way a month ago. Please accept the submitted patch to ensure correct behavior.
