### ISSUE TITLE
Delete nginx config

### ISSUE THREAD

**Issue by jvanbaarsen** [miketheman/nginx#333]
Hi,

I'm probably just not looking in the correct place, but I can't seem to find a way to remove an site from sites-enabled/site-available once it is created.

I tried the following:

```
    nginx_site "myapp.conf", enable: false
```

and

```
    nginx_site "myapp.conf" do
      action [:disable, :delete]
    end
```

Is this an unsupported feature? Or am I missing something?

Regards,

**Comment by jedi4ever** [comment]
@jvanbaarsen we just used 'link' action :delete

**Comment by jvanbaarsen** [comment]
@jedi4ever Yeah thats the way I approeached it right now. I unlink the sites-enabled entry, and delete the sites-available entry.
