### ISSUE TITLE
node['nginx']['group'] default attribute improperly set

### ISSUE THREAD

**Issue by stevenolen** [miketheman/nginx#334]
Noticed this on ubuntu 14.04 & 12.04 (well, based on the logic, it should really happen everywhere) after the commits made in the past day.  

https://github.com/miketheman/nginx/blob/master/attributes/default.rb#L73

appears to resolve to `{}` instead of 'www-data' and instead should be:
`default['nginx']['group'] = node['nginx']['group'] || node['nginx']['user']`

Submitting PR, but wanted an issue in case further discussion was required..

**Comment by miketheman** [comment]
Thanks!
