### ISSUE TITLE
issues since last chef-nginx publish to supermarket

### ISSUE THREAD

**Issue by jedi4ever** [miketheman/nginx#336]
- after initial run we could not /etc/init.d/nginx reload (it would say reloading fail) ; it required a hard kill nginx (stop, start , restart did not work)
- also we wrote config files without the '.conf' extension , those are not anymore included in the nginx config

just for the record

**Comment by jedi4ever** [comment]
This bit us - https://github.com/miketheman/nginx/blob/master/attributes/default.rb#L44

We used the chef-cookbook before and it installed pid in /var/run/nginx.pid not in /run/nginx.pid

**Comment by runningman84** [comment]
The nginx.pid works for me in Ubuntu 14.04. 

Only allowing sites with .conf ending was a big break for us. My aws instances lost all their active websites and were autoscaled again and again... (until I found the underlying problem)
It is not mentioned anywhere that sites should have a .conf ending.

**Comment by runningman84** [comment]
Even the cookbook itself doesn't use a .conf suffix for its sites:
https://github.com/miketheman/nginx/blob/master/recipes/commons_conf.rb

**Comment by miketheman** [comment]
Merged #338. Will likely release it tonight.

**Comment by phillipsnick** [comment]
Was bitten by the pid location change on ubuntu and the .conf removal on this. Seems like some pretty big changes for a patch version release?

**Comment by miketheman** [comment]
Released 2.7.6.

There's been a bunch of changes - and unfortunately I missed that one in testing. My apologies.
