### ISSUE TITLE
Ohai custom plugin reloads on every converge

### ISSUE THREAD

**Issue by RobertNorthard** [miketheman/nginx#344]
The Ohai plugin is reloaded on every Chef run and therefore is not idempotent as a resource is registered as updating.

Please see log output below.

       [2015-03-28T23:46:10+00:00] INFO: Processing ohai[custom_plugins] action reload (ohai::default line 47)
       [2015-03-28T23:46:11+00:00] INFO: ohai[custom_plugins] reloaded
           - re-run ohai and merge results into node attributes

**Comment by rmoriz** [comment]
Probable ohai-cookbook issue, see referenced issue.

**Comment by rmoriz** [comment]
just to keep this issue updated: It's a bug in the `ohai` cookbook that can be "circumvented" by also using the `chef-client` cookbook which sets Ohai's plugin_path - this prevents the reloading logic. Sucks for CI/CD but might be a solution for deployments, especially typical chef-server deployments where `chef-client` needs to be installed a as a service.

**Comment by RobertNorthard** [comment]
@rmoriz thanks for the update.
