### ISSUE TITLE
Setting custom configurations like real_ip_header, set_real_ip_from

### ISSUE THREAD

**Issue by erez-rabih** [miketheman/nginx#352]
Hi,

Is it possible to set custom NginX configurations like the two above using attributes or do I have to use my own ERB template to achieve that?

Thanks.

**Comment by rmoriz** [comment]
see https://github.com/miketheman/nginx/blob/master/recipes/http_realip_module.rb

you can se via attributes:

```
node.default['nginx']['realip']['header']            = 'X-Forwarded-For'
node.default['nginx']['realip']['addresses']         = ['127.0.0.1']
node.default['nginx']['realip']['real_ip_recursive'] = 'off'
```

see also http://nginx.org/en/docs/http/ngx_http_realip_module.html (=> "Context"). You can define it in your custom vhost, too.

If you need a customized template, I would consider using [chef-rewind](https://github.com/thommay/chef-rewind) and a wrapper cookbook.

**Comment by erez-rabih** [comment]
Thanks for the answer. Pretty much covered what I needed :)
