### ISSUE TITLE
can't create directory on nginx start

### ISSUE THREAD

**Issue by daften** [miketheman/nginx#361]
I get the error  ```nginx: [emerg] mkdir() "/var/lib/nginx/speed" failed (2: No such file or directory)```
This only happens when i use the cookbook, not on package install. This is for an install of aegir.

**Comment by daften** [comment]
Circumvented by using
```
directory '/var/lib/nginx' do
  owner 'root'
  group 'root'
  mode '0755'
end
```

**Comment by rmoriz** [comment]
which distro, version, run_list?

**Comment by daften** [comment]
It's Ubuntu 14.04, but I've traced it to nginx-hardening (https://github.com/hardening-io/chef-nginx-hardening). Just having it in the metadata as a dependency is enough to disallow aegir to restart nginx. After a reboot, everything seems fine.

**Comment by daften** [comment]
Closed because there's a workaround, and the main problems seem to be caused by another cookbook in the run_list
