### ISSUE TITLE
Is this still in progress?

### ISSUE THREAD

**Issue by computerlyrik** [miketheman/nginx#386]
Hey there!

I'd like to join forces. I need a resource setting up proxy hosts for me.

Is your 3.0-rewrite-intention still alive? How can i help out?

**Comment by miketheman** [comment]
Hi there!

3.0 rewrite is very much the goal - I've had some slowdown in getting around to testing the centos/systemd stuff: https://github.com/miketheman/nginx/pull/384

I'm already using the Ubuntu one in a production environment - and as long as you mentally remember that it's not `/var/log/nginx/` - rather /var/log/nginx-<name>`, things are ok.

There's still some stuff that needs to be figured out - as in how many more things cannot be placed inside the sites-enabled/ file and must be in the root resource.

Also, the rewrite takes the stance of "this cookbook should _not_ be compiling nginx for you on every target server" - rather you _should_ build & distribute binaries (packages!) out of the scope of running servers.

**Comment by scalp42** [comment]
Piggy backing on @miketheman here, https://github.com/cubicdaiya/nginx-build is a great tool for this.

**Comment by miketheman** [comment]
@scalp42 That's cool, hadn't seen that one. I'm more like to go with [fpm-cookery](https://github.com/bernd/fpm-cookery), and modify a recipe with my flags like so: https://github.com/bernd/fpm-recipes/blob/master/nginx/recipe.rb

The resulting package can then be stuffed in a package repo, packagecloud, etc.

**Comment by miguelaferreira** [comment]
BTW I'm using the centos/systemd features of #384 in production as well

**Comment by miketheman** [comment]
Closing this question in favor of the [release tracking checklist](https://github.com/miketheman/nginx/issues/397).
Thanks!
