### ISSUE TITLE
Temperature poll: Upstart support yes/no?

### ISSUE THREAD

**Issue by miketheman** [miketheman/nginx#402]
Considering:

- Upstart support is waning rapidly, but still the primary init system for Ubuntu 12/14 LTS releases
- SysV Init scripts are ubiquitous
- SystemD is the new kid on the block, crowding out Upstart

**Question: Is it worthwhile to continue to try and support upstart mechanics?**

If no, then they will be scrubbed in favor of the SysV init scripts, and support systemd when possible.

The burden of support and testing grows higher with each iteration of bug fix/behavior change to the process control procedure.

Use [GitHub's reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to this question to weigh in (a :-1: means "don't support upstart any more")

Reserve comments for constructive discussion.

**Comment by scalp42** [comment]
One thing to keep in mind also is that nginx package ships with Upstart config by default unless I'm wrong.

**Comment by miketheman** [comment]
Resolved: Continue to support upstart mechanism until 14.04 EOL (~2019).
