### ISSUE TITLE
Issue installing this cookbook via librarian-chef

### ISSUE THREAD

**Issue by lucke84** [miketheman/nginx#410]
I have a Cheffile which includes this cookbook:
```
# cookbook 'nginx', git: 'git://github.com/opscode-cookbooks/nginx.git' #old URL
cookbook 'nginx', git: 'git://github.com/miketheman/nginx.git'
```

because the old one (opscode-cookbooks) was giving me this error:
```
[...]
Installing nginx (2.7.6)
fatal: reference is not a tree: e36944b0dac1f21044a4f0d01fc566023325cfde
```

If I run: `librarian-chef install` I get:
```
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Ruby: 2.3.1 (but I get the same with 2.2.5) and 
```
librarian (0.1.2)
librarian-chef (0.0.4)
```

If I comment out this cookbook from the `Cheffile`, `librarian-chef` can complete the installation of all the other cookbooks. Any pointers to what could be causing this?

**Comment by xymor** [comment]
There's no master branch in the repo, try:
cookbook "mysql", git: "https://github.com/opscode-cookbooks/mysql.git", branch: "3.0.0-rewrite"

Or some other: https://github.com/miketheman/nginx/branches/all

**Comment by lucke84** [comment]
The `branch` keyword doesn't seem to be supported, but you can use `ref`:

```
cookbook 'nginx', git: 'git://github.com/miketheman/nginx.git', ref: '3.0.0-rewrite'
```

Thanks @xymor !
