### ISSUE TITLE
Documentation does not mention important info about named locations at try_files

### ISSUE THREAD

**Issue by KES777** [miketheman/nginx#417]
[This](http://stackoverflow.com/questions/21286850/nginx-try-files-with-multiple-named-locations#comment32106501_21294752) is original post.

In short there is no info about how to use many named locations at `try_files` directive

**Comment by miketheman** [comment]
@KES777 This seems to be a documentation issue for the nginx project, not the nginx Chef Cookbook, which is this repo.

I recommend you examine the nginx project here: https://trac.nginx.org/nginx/
